project:
  type: website
  output-dir: docs
website:
  title: "DPE"
  navbar:
    left:
      - text: A propos
        href: index.qmd
      - text: Préparation des Données
        menu:
          - text: Choix de la zone d'étude
            href: choix_geom.qmd
          - text: Extraction des DPE
            href: choix_dpe.qmd
      - text: Exploration statistique
        menu:
          - text: Les quartiers de Rouen
            href: explor1_rouen.qmd
    right: 
      - icon: github # add icons as navbar buttons
        href: https://github.com/worldregio/dpe2025
        target: _blank
  page-footer:
    background: dark
    left: Copyright 2025-2026, Claude Grasland
format:
  html:
    theme: 
      light: minty    
      dark: solar
    css: styles.css
    toc: true


